name: starter_flutter
description: Starter template for Flutter apps.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

# https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  android: true
  image_path_android: 'assets/icons/android.png'
  adaptive_icon_background: '#00ff00'
  adaptive_icon_foreground: 'assets/icons/android-foreground.png'

  ios: true
  image_path_ios: 'assets/icons/ios.png'

  macos:
    generate: true
    image_path: 'assets/icons/macos.png'

  web:
    generate: true
    image_path: 'assets/icons/web.png'
    background_color: '#00ff00'
    theme_color: '#00ff00'
